common: &common
  adapter: postgresql
  min_messages: warning
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  prepared_statements: false

development:
  <<: *common
  database: camping_gear_dev

test:
  <<: *common
  database: camping_gear_test

production:
  <<: *common
  database: camping_gear
